[package]
name = "sorting-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21"
rand = "0.8.5"
strum = "0.24"
strum_macros = "0.24"
cfg-if = "1.0.0"
